In [8]:
#Import Numpy
import numpy as np


In [9]:
###print Numpy version
print("Numpy Version:", np.__version__)
np.show_config()

Numpy Version: 2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: 

In [13]:
#create null vector size 10
null_vectors=np.zeros(10 , dtype=int)
print(null_vectors)


[0 0 0 0 0 0 0 0 0 0]


In [15]:
###Find memory size of an array
arr=np.array([1,0,1])
print(arr.size)
print(arr.itemsize)
print("memory size",arr.size*arr.itemsize)

3
8
memory size 24


In [18]:
##Create null vector of size 10 and 5th element is 1
vector=np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [21]:
###Reverse a vector
vector=[1,3,4,5,2]
reverse_vector=vector[::-1]
print(reverse_vector)

[2, 5, 4, 3, 1]


In [23]:
##print a range of vectors
vec=np.arange(10,49)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [26]:
###create a 3X3 Matrices from 0 to 8
matrix=np.matrix([[0,1,2],[3,4,5],[6,7,8]])
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
##Find indices of non-zero elements from [1,2,0,0,4,0]
v=[1,2,0,0,4,0]
index=np.nonzero(v)
print(index)

(array([0, 1, 4]),)


In [30]:
##create 3X3 Identity matrix
I=np.identity(3 , dtype=int)
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [33]:
###create a 3X3X3 array with random numbers
a=np.random.rand(3,3,3)
print(a)


[[[0.8763838  0.08236756 0.1636118 ]
  [0.25624789 0.20741469 0.02909169]
  [0.80927831 0.03777988 0.70285292]]

 [[0.80043639 0.83614314 0.92333819]
  [0.03459626 0.04059164 0.1526843 ]
  [0.80558245 0.7291117  0.01536386]]

 [[0.47869553 0.72941477 0.94445137]
  [0.40231185 0.26386755 0.69467999]
  [0.59361924 0.30522647 0.96206086]]]


In [35]:
###create a 10X10 array with random values and find maximum and minimum values
array=np.random.rand(10,10)
print(array)
print("maximum value:",array.max())
print("minimum value:",array.min())

[[0.50564983 0.5184755  0.88337289 0.53077772 0.32767179 0.84767209
  0.06482509 0.26197083 0.87199534 0.81981825]
 [0.72700206 0.14740078 0.89713735 0.43995168 0.03646587 0.38935263
  0.09596352 0.82973648 0.59245806 0.13625936]
 [0.52909327 0.67391847 0.93702539 0.01424984 0.21315731 0.68036966
  0.64772505 0.39463041 0.76492862 0.46093271]
 [0.80020765 0.99999179 0.84656461 0.33458129 0.25427188 0.40424612
  0.24259285 0.26157538 0.82566863 0.58843849]
 [0.82621635 0.8464184  0.11351306 0.4383625  0.67895917 0.82146084
  0.75036083 0.17597676 0.2023117  0.4238943 ]
 [0.91248826 0.7896284  0.80018177 0.96953906 0.95754419 0.5423016
  0.53261132 0.5985823  0.32970696 0.77381646]
 [0.51544262 0.5272864  0.33590639 0.46610935 0.83919815 0.6602191
  0.86779868 0.51887932 0.7105738  0.25169685]
 [0.55211776 0.08039458 0.41014924 0.59268062 0.54430827 0.76391699
  0.1339475  0.39448528 0.63023086 0.96443123]
 [0.24893934 0.60472621 0.03822861 0.04387385 0.94499326 0.03032936
  0.79495434 0

In [36]:
###create a random vector of size 30 and find mean
array=np.random.rand(30)
print(array)
print("mean",array.mean())

[0.63162842 0.52124223 0.59607574 0.23316413 0.08648575 0.44154999
 0.71424878 0.60178686 0.69066753 0.31658822 0.11738741 0.85158997
 0.59657383 0.92697663 0.82280273 0.97743722 0.57346354 0.62296939
 0.49911264 0.77840369 0.2565453  0.29814849 0.53457708 0.95558906
 0.45477984 0.78368157 0.67370122 0.76466525 0.13975108 0.65861586]
mean 0.5706736476718387


In [42]:
###Create 2D array with 1 on the border and 0 inside
arr=np.ones((5,5) ,dtype=int)
arr[1:-1,1:-1]=0
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [45]:
##How to add a border (filled with 0's) around an existing array
arr=np.ones((5,5), dtype=int)
bordered_arr=np.pad(arr,pad_width=1,mode='constant',constant_values=0)
print(bordered_arr)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


In [46]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [49]:
## Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix=np.zeros((5,5), dtype=int)
values=[1,2,3,4]
np.fill_diagonal(matrix[1:], values)
print (matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [56]:
#create a checkboard pattern
rows,cols=np.indices((8,8))
checkboard=(rows+cols)%2
print(checkboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [59]:
##Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
arr=np.arange(6*7*8).reshape((6,7,8))
print(np.unravel_index(99,(6,7,8)))


(np.int64(1), np.int64(5), np.int64(3))


In [64]:
 ###Create a checkerboard 8x8 matrix using the tile function
arr=np.tile(([0,1],[1,0]),(4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [69]:
###Normalize a 5x5 random matrix
z=np.random.rand(5,5)
zmin,zmax=z.min(),z.max()
z_norm=z-zmin/zmax-zmin
print(z_norm)

[[ 3.83981635e-01  5.89200889e-01  3.55700738e-01  5.52875344e-01
   7.55653483e-01]
 [ 9.09696071e-01 -3.02891918e-02  9.15650293e-01  4.45378692e-01
   8.50776117e-01]
 [ 5.02418011e-01  3.55633410e-01  3.55824611e-01  8.59395024e-01
   8.57036874e-01]
 [ 7.72278365e-01  5.95556398e-03  9.25210322e-01  8.96701082e-01
   9.35745025e-01]
 [ 2.18353950e-01  6.26156953e-01  6.41934667e-01  4.31489104e-04
   4.86253599e-01]]
